
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;


public class update extends javax.swing.JFrame {
String url1,name1,pass1,db_name1;
String n ,n1,n2,n3,n4,n5,n6;
int num=0;
    /**
     * Creates new form update
     */
    public update() {
        initComponents();
        setLocationRelativeTo(null);  
    }

    update(String url, String name, String pass, String dbname) {
     url1=url;
     name1=name;
     pass1=pass;
     db_name1=dbname;
        initComponents();
        setLocationRelativeTo(null);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op1 = new javax.swing.JOptionPane();
        l2 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        l7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Entry");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton3.setText("Update values");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Table Name");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squre/sqredback32.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Get Column Names");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squre/sqredinfo32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(30, 30, 30)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t5)
                            .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t6)
                            .addComponent(l4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t7)
                            .addComponent(l5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t8)
                            .addComponent(l6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jButton3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i=1;
        String c,c1,c2,c3,c4,c5,c6,name;

        c=t3.getText();
        c1=t4.getText();
        c2=t5.getText();
        c3=t6.getText();
        c4=t7.getText();
        c5=t8.getText();
        c6=t9.getText();

        name=t2.getText();
       
        final String db_url="jdbc:mysql://"+url1+"/"+db_name1;
        final String uid=name1;
        final String pass=pass1;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(db_url,uid,pass);
            Statement stmt=con.createStatement();
             
            switch (num) {
                case 2:
                stmt.executeUpdate("update "+name+" set "+n+"='" + c + "',"+n1+"='" + c1 + "' where "+n+"='"+c+"'"
                );
                op1.showMessageDialog(null,"Values Updated Successfully");
                break;
                case 3:
                stmt.executeUpdate("update "+name+" set "+n+"='" + c + "',"+n1+"='" + c1 + "',"+n2+"='" + c2 + "' where "+n+"='"+c+"'"
                );
                op1.showMessageDialog(null,"Values Updated Successfully");
                break;
                case 4:
                stmt.executeUpdate("update "+name+" set "+n+"='" + c + "',"+n1+"='" + c1 + "',"+n2+"='" + c2 + "',"+n3+"='" + c3 + "' where "+n+"='"+c+"'"
                );
                op1.showMessageDialog(null,"Values Updated Successfully");
                break;
                case 5:
                stmt.executeUpdate("update "+name+" set "+n+"='" + c + "',"+n1+"='" + c1 + "',"+n2+"='" + c2 + "',"+n3+"='" + c3 + "',"+n4+"='" + c4 + "' where "+n+"='"+c+"'"
                );
                op1.showMessageDialog(null,"Values Updated Successfully");
                break;
                case 6:
                stmt.executeUpdate("update "+name+" set "+n+"='" + c + "',"+n1+"='" + c1 + "',"+n2+"='" + c2 + "',"+n3+"='" + c3 + "',"+n4+"='" + c4 + "',"+n5+"='" + c5 + "' where "+n+"='"+c+"'"
                );
                op1.showMessageDialog(null,"Values Updated Successfully");
                break;
                case 7:
                stmt.executeUpdate("update "+name+" set "+n+"='" + c + "',"+n1+"='" + c1 + "',"+n2+"='" + c2 + "',"+n3+"='" + c3 + "',"+n4+"='" + c4 + "',"+n5+"='" + c5 + "',"+n6+"='" + c6 + "' where "+n+"='"+c+"'"
                );
                op1.showMessageDialog(null,"Values Updated Successfully");
                break;
                default:
                break;
            }
            jButton2.setEnabled(false);
            t3.setText("");
            t4.setText("");
            t5.setText("");
            t6.setText("");
            t7.setText("");
            t8.setText("");
            t9.setText("");
            /*this.setVisible(false);
            new Table_operations(url1,name1,pass1,db_name1).setVisible(true);*/
        }
        catch(Exception e)
        {
            op1.showMessageDialog(null,e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new Table_operations(url1,name1,pass1,db_name1).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name=t2.getText();
        
        if(name.equals("")){
            op1.showMessageDialog(null,"Please Enter Table Name");
        }
        else{
            int i=1;
            
            final String db_url="jdbc:mysql://"+url1+"/"+db_name1;
            final String uid=name1;
            final String pass=pass1;
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection(db_url,uid,pass);
                Statement stmt=con.createStatement();
                ResultSet rs1=stmt.executeQuery("describe "+name+"");
           while(rs1.next()){
              String one1=rs1.getString("Field");
              num++;
           }
           switch (num) {
    case 7:
        jLabel2.setVisible(true);
        l1.setVisible(true);
        l2.setVisible(true);
        l3.setVisible(true);
        l4.setVisible(true);
        l5.setVisible(true);
        l6.setVisible(true);
        l7.setVisible(true);
        t2.setVisible(true);
        t3.setVisible(true);
        t4.setVisible(true);
        t5.setVisible(true);
        t6.setVisible(true);
        t7.setVisible(true);
        t8.setVisible(true);
        t9.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    break;
    case 6:
      jLabel2.setVisible(true);
        l1.setVisible(true);
        l2.setVisible(true);
        l3.setVisible(true);
        l4.setVisible(true);
        l5.setVisible(true);
        l6.setVisible(true);
        
        t2.setVisible(true);
        t3.setVisible(true);
        t4.setVisible(true);
        t5.setVisible(true);
        t6.setVisible(true);
        t7.setVisible(true);
        t8.setVisible(true);
        
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    break; 
    case 5:
        jLabel2.setVisible(true);
        l1.setVisible(true);
        l2.setVisible(true);
        l3.setVisible(true);
        l4.setVisible(true);
        l5.setVisible(true);
        t2.setVisible(true);
        t3.setVisible(true);
        t4.setVisible(true);
        t5.setVisible(true);
        t6.setVisible(true);
        t7.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    break;
    case 4:
        jLabel2.setVisible(true);
        l1.setVisible(true);
        l2.setVisible(true);
        l3.setVisible(true);
        l4.setVisible(true);
        t2.setVisible(true);
        t3.setVisible(true);
        t4.setVisible(true);
        t5.setVisible(true);
        t6.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    break;
    case 3:
        jLabel2.setVisible(true);
        l1.setVisible(true);
        l2.setVisible(true);
        l3.setVisible(true);
        
        t2.setVisible(true);
        t3.setVisible(true);
        t4.setVisible(true);
        t5.setVisible(true);
        
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    break;
    default:
        jLabel2.setVisible(true);
        l1.setVisible(true);
        l2.setVisible(true);
        t2.setVisible(true);
        t3.setVisible(true);
        t4.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        break;
}
                switch (num) {
                     case 2:{
                        ResultSet rs=stmt.executeQuery("describe "+name+"");
                        while(rs.next()){
                            String one=rs.getString("Field");

                            if(i==1){
                                l1.setText(""+one);
                                n=one;
                            }
                            else {
                                l2.setText(""+one);
                                n1=one;
                            }
                            
                            i++;
                        }
                        break;
                    }
                    case 3:{
                        ResultSet rs=stmt.executeQuery("describe "+name+"");
                        while(rs.next()){
                            String one=rs.getString("Field");

                            if(i==1){
                                l1.setText(""+one);
                                n=one;
                            }
                            else if(i==2){
                                l2.setText(""+one);
                                n1=one;
                            }
                            else{
                                l3.setText(""+one);
                                n2=one;
                            }
                            i++;
                        }
                        break;
                    }
                    case 4:{
                        ResultSet rs=stmt.executeQuery("describe "+name+"");
                        while(rs.next()){
                            String one=rs.getString("Field");

                            if(i==1){
                                l1.setText(""+one);
                                n=one;
                            }
                            else if(i==2){
                                l2.setText(""+one);
                                n1=one;
                            }
                            else if(i==3){
                                l3.setText(""+one);
                                n2=one;
                            }
                            else{
                                l4.setText(""+one);
                                n3=one;
                            }
                            i++;
                        }
                        break;
                    }
                    case 5:{
                        ResultSet rs=stmt.executeQuery("describe "+name+"");
                        while(rs.next()){
                            String one=rs.getString("Field");

                            if(i==1){
                                l1.setText(""+one);
                                n=one;
                            }
                            else if(i==2){
                                l2.setText(""+one);
                                n1=one;
                            }
                            else if(i==3){
                                l3.setText(""+one);
                                n2=one;
                            }
                            else if(i==4){
                                l4.setText(""+one);
                                n3=one;
                            }
                            else{
                                l5.setText(""+one);
                                n4=one;
                            }
                            i++;
                        }
                        break;
                    }
                    case 6:{
                        ResultSet rs=stmt.executeQuery("describe "+name+"");
                        while(rs.next()){
                            String one=rs.getString("Field");

                            if(i==1){
                                l1.setText(""+one);
                                n=one;
                            }
                            else if(i==2){
                                l2.setText(""+one);
                                n1=one;
                            }
                            else if(i==3){
                                l3.setText(""+one);
                                n2=one;
                            }
                            else if(i==4){
                                l4.setText(""+one);
                                n3=one;
                            }
                            else if(i==5){
                                l5.setText(""+one);
                                n4=one;
                            }
                            else{
                                l6.setText(""+one);
                                n=one;
                            }
                            i++;
                        }
                        break;
                    }
                    default:{
                        ResultSet rs=stmt.executeQuery("describe "+name+"");
                        while(rs.next()){
                            String one=rs.getString("Field");

                            if(i==1){
                                l1.setText(""+one);
                                n=one;
                            }
                            else if(i==2){
                                l2.setText(""+one);
                                n1=one;
                            }
                            else if(i==3){
                                l3.setText(""+one);
                                n2=one;
                            }
                            else if(i==4){
                                l4.setText(""+one);
                                n3=one;
                            }
                            else if(i==5){
                                l5.setText(""+one);
                                n4=one;
                            }
                            else if(i==6){
                                l6.setText(""+one);
                                n5=one;
                            }
                            else{
                                l7.setText(""+one);
                                n6=one;
                            }
                            i++;
                        }
                        break;
                    }
                }

            }

            catch(Exception e)
            {
                op1.showMessageDialog(null,e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//jLabel2.setVisible(false);
//t2.setVisible(false);
t3.setVisible(false);
t4.setVisible(false);
t5.setVisible(false);
t6.setVisible(false);
t7.setVisible(false);
t8.setVisible(false);
t9.setVisible(false);
l1.setVisible(false);
l2.setVisible(false);
l3.setVisible(false);
l4.setVisible(false);
l5.setVisible(false);
l6.setVisible(false);
l7.setVisible(false);
//jButton2.setVisible(false);
jButton3.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             op1.showMessageDialog(null,"Enter the table name and then enter all \ndata to update record with new vales \nNote: All fields must be filled even if only \none value is to be updated");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JOptionPane op1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
